emojis:
  - name: ai_thinking
    emoji: ":loading:"

  - name: google_search_tool_artifact_icon
    emoji: ğŸŒ
  - name: markitdown_crawler_tool_artifact_icon
    emoji: ğŸ“‘
  - name: get_slack_conversation_replies_tool_artifact_icon
    emoji: ğŸ’¬

messages:
  - name: content_disclaimer_message
    text: ğŸ¤” AI å¯èƒ½æœƒç™¼ç”ŸéŒ¯èª¤ï¼Œè«‹æŸ¥æ ¸é‡è¦è³‡è¨Šã€‚
  - name: new_conversation_title
    text: é–‹å•Ÿæ–°çš„å°è©±
  - name: new_conversation_message
    text: ğŸ’¡ é–‹å•Ÿæ–°çš„å°è©±
  - name: tool_artifact_title
    text: åƒè€ƒè³‡æ–™
  - name: ai_reply_too_long_warning_message
    text: è¨Šæ¯éé•·ï¼Œå·²æˆªæ–·...

  - name: assistant_placeholder
    text: å•å• AIï¼Œç„¡æ‰€ä¸èƒ½ï¼
  - name: assistant_thinking
    text: æ­£åœ¨æ€è€ƒ...
  - name: assistant_greeting
    text: ä»Šå¤©éçš„å¥½å—?

  - name: assistant_greeting_prompt_0_title
    text: æ‰“æ‹›å‘¼
  - name: assistant_greeting_prompt_0_icon
    text: ğŸ¤—
  - name: assistant_greeting_prompt_0_message
    text: æˆ‘ä»Šå¤©éå¾—å¾ˆå¥½ï¼Œç¾åœ¨å¹¾é»?

  - name: assistant_greeting_prompt_1_title
    text: æ‰¾é¤å»³
  - name: assistant_greeting_prompt_1_icon
    text: ğŸ´
  - name: assistant_greeting_prompt_1_message
    text: å¹«æˆ‘æ‰¾å°åŒ—å¸‚å¥½åƒçš„ç‡’çƒ¤é¤å»³ï¼Œ1000å…ƒä»¥å…§ã€‚

  - name: assistant_greeting_prompt_2_title
    text: è§£æ•¸å­¸å•é¡Œ
  - name: assistant_greeting_prompt_2_icon
    text: ğŸ“š
  - name: assistant_greeting_prompt_2_message
    text: è«‹å¹«æˆ‘è§£é€™å€‹å¾®ç©åˆ†å•é¡Œï¼šæ±‚å‡½æ•¸ f(x) = x^2 * sin(x) åœ¨å€é–“ [0, Ï€] ä¸Šçš„å®šç©åˆ†ã€‚

  - name: assistant_greeting_prompt_3_title
    text: é–‹ç™¼æ¼”ç®—æ³•
  - name: assistant_greeting_prompt_3_icon
    text: ğŸ’»
  - name: assistant_greeting_prompt_3_message
    text: æä¾›çµ¦æˆ‘ Python å¿«é€Ÿæ’åºç¨‹å¼ç¢¼ç¯„ä¾‹ã€‚

  - name: assistant_greeting_prompt_4_title
    text: åˆ†æå¤©æ°£è¶¨å‹¢
  - name: assistant_greeting_prompt_4_icon
    text: ğŸŒ¤ï¸
  - name: assistant_greeting_prompt_4_message
    text: |
      æœå°‹ "ä»Šå¤©å°åŒ—å¤©æ°£"
      ä¸¦å¾æœå°‹çµæœä¸­ä¾†è‡ª "accuweather.com" ç¶²ç«™çš„é€£çµè£¡
      æŠ“å–å…§å®¹æ‰¾åˆ°å¯ä»¥æŸ¥è©¢æœªä¾†ä¸€å‘¨å°åŒ—å¤©æ°£çš„é€£çµ
      æœ€å¾ŒæŠ“å– "æ¯å¤©" é€£çµç¶²é å…§å®¹
      ä¸¦æä¾›æœªä¾†ä¸€å‘¨å°åŒ—å¤©æ°£çš„æ‘˜è¦

  - name: assistant_greeting_prompt_5_title
    text: å€‹è‚¡æ¯”è¼ƒ
  - name: assistant_greeting_prompt_5_icon
    text: ğŸ“ˆ
  - name: assistant_greeting_prompt_5_message
    text: |
      æœå°‹ä¸¦æ¯”è¼ƒ "å°ç©é›» 2330" å’Œ "è¯ç™¼ç§‘ 2454" çš„ï¼š
      1. æœ€è¿‘ä¸€å­£çš„è²¡å‹™è¡¨ç¾
      2. æœ¬ç›Šæ¯”å’Œæ®–åˆ©ç‡
      3. æŠ€è¡“é¢æŒ‡æ¨™
      4. å¸‚å ´è©•åƒ¹
      æœ€å¾Œæä¾›ä¸€å€‹ä»¥ä¸Šè³‡è¨Šçš„æ‘˜è¦

  - name: assistant_greeting_prompt_6_title
    text: è§£é‡‹ Slack è¨Šæ¯
  - name: assistant_greeting_prompt_6_icon
    text: ğŸ’¬
  - name: assistant_greeting_prompt_6_message
    text: |
      https://helenworkspacegroup.slack.com/archives/C03DQ95UCQ4/p1746751656423869
      é€™å¯«ç”šéº¼?
