emojis:
  - name: ai_thinking
    emoji: ":loading:"

  - name: google_search_tool_artifact_icon
    emoji: ğŸŒ
  - name: markitdown_crawler_tool_artifact_icon
    emoji: ğŸ“‘
  - name: get_slack_conversation_replies_tool_artifact_icon
    emoji: ğŸ’¬
  - name: get_slack_conversation_history_tool_artifact_icon
    emoji: ğŸ’¬
  - name: search_slack_conversation_tool_artifact_icon
    emoji: ğŸ”

messages:
  - name: content_disclaimer_message
    text: ğŸ¤” AI å¯èƒ½æœƒç™¼ç”ŸéŒ¯èª¤ï¼Œè«‹æŸ¥æ ¸é‡è¦è³‡è¨Šã€‚
  - name: new_conversation_title
    text: æ–°å°è©±
  - name: new_conversation_message
    text: ğŸ’¡ é–‹å•Ÿæ–°çš„å°è©±
  - name: tool_artifact_title
    text: åƒè€ƒè³‡æ–™
  - name: ai_reply_too_long_warning_message
    text: è¨Šæ¯éé•·ï¼Œå·²æˆªæ–·...

  - name: assistant_placeholder
    text: å•å• AIï¼Œç„¡æ‰€ä¸èƒ½ï¼
  - name: assistant_thinking
    text: æ­£åœ¨æ€è€ƒ...
  - name: assistant_greeting
    text: ä»Šå¤©éçš„å¥½å—?

  - name: assistant_greeting_prompt_00_title
    text: æ‰“æ‹›å‘¼
  - name: assistant_greeting_prompt_00_icon
    text: ğŸ¤—
  - name: assistant_greeting_prompt_00_message
    text: æˆ‘ä»Šå¤©éå¾—å¾ˆå¥½ï¼Œç¾åœ¨å¹¾é»?

  - name: assistant_greeting_prompt_01_title
    text: æ‰¾é¤å»³
  - name: assistant_greeting_prompt_01_icon
    text: ğŸ´
  - name: assistant_greeting_prompt_01_message
    text: å¹«æˆ‘æ‰¾å°åŒ—å¸‚å¥½åƒçš„ç‡’çƒ¤é¤å»³ï¼Œ1000å…ƒä»¥å…§ã€‚

  - name: assistant_greeting_prompt_02_title
    text: è§£æ•¸å­¸å•é¡Œ
  - name: assistant_greeting_prompt_02_icon
    text: ğŸ“š
  - name: assistant_greeting_prompt_02_message
    text: |
      è«‹å¹«æˆ‘è§£é€™å€‹å¾®ç©åˆ†å•é¡Œï¼šæ±‚å‡½æ•¸ f(x) = x^2 * sin(x) åœ¨å€é–“ [0, Ï€] ä¸Šçš„å®šç©åˆ†ã€‚
      ä¸¦ä¸”æä¾›è©³ç´°çš„è§£é¡Œéç¨‹ã€‚
      å¦‚æœä½ ä¸çŸ¥é“æ€éº¼è§£ï¼Œè«‹ä¸Šç¶²æœå°‹ã€‚

  - name: assistant_greeting_prompt_03_title
    text: é–‹ç™¼æ¼”ç®—æ³•
  - name: assistant_greeting_prompt_03_icon
    text: ğŸ’»
  - name: assistant_greeting_prompt_03_message
    text: æä¾›çµ¦æˆ‘ Python å¿«é€Ÿæ’åºç¨‹å¼ç¢¼ç¯„ä¾‹ã€‚

  - name: assistant_greeting_prompt_04_title
    text: åˆ†æå¤©æ°£è¶¨å‹¢
  - name: assistant_greeting_prompt_04_icon
    text: ğŸŒ¤ï¸
  - name: assistant_greeting_prompt_04_message
    text: |
      æœå°‹ "ä»Šå¤©å°åŒ—å¤©æ°£"
      ä¸¦å¾æœå°‹çµæœä¸­ä¾†è‡ª "accuweather.com" ç¶²ç«™çš„é€£çµè£¡
      æŠ“å–å…§å®¹æ‰¾åˆ°å¯ä»¥æŸ¥è©¢æœªä¾†ä¸€å‘¨å°åŒ—å¤©æ°£çš„é€£çµ
      æœ€å¾ŒæŠ“å– "æ¯å¤©" é€£çµç¶²é å…§å®¹
      ä¸¦æä¾›æœªä¾†ä¸€å‘¨å°åŒ—å¤©æ°£çš„æ‘˜è¦

  - name: assistant_greeting_prompt_05_title
    text: å€‹è‚¡æ¯”è¼ƒ
  - name: assistant_greeting_prompt_05_icon
    text: ğŸ“ˆ
  - name: assistant_greeting_prompt_05_message
    text: |
      æœå°‹ä¸¦æ¯”è¼ƒ "å°ç©é›» 2330" å’Œ "è¯ç™¼ç§‘ 2454" çš„ï¼š
      1. æœ€è¿‘ä¸€å­£çš„è²¡å‹™è¡¨ç¾
      2. æœ¬ç›Šæ¯”å’Œæ®–åˆ©ç‡
      3. æŠ€è¡“é¢æŒ‡æ¨™
      4. å¸‚å ´è©•åƒ¹
      æœ€å¾Œæä¾›ä¸€å€‹ä»¥ä¸Šè³‡è¨Šçš„æ‘˜è¦

  - name: assistant_greeting_prompt_10_title
    text: è§£é‡‹ Slack è¨Šæ¯
  - name: assistant_greeting_prompt_10_icon
    text: ğŸ’¬
  - name: assistant_greeting_prompt_10_message
    text: |
      https://wei840222-home-infra.slack.com/archives/C08VB4JEELX/p1749635140000399
      é€™å¯«ç”šéº¼?
  - name: assistant_greeting_prompt_11_title
    text: Slack é »é“æ´å¯Ÿ
  - name: assistant_greeting_prompt_11_icon
    text: ğŸ’¬
  - name: assistant_greeting_prompt_11_message
    text: |
      https://wei840222-home-infra.slack.com/archives/C090F9D535M
      çµ±æ•´é€™é »é“æœ€è¿‘20å‰‡è¨Šæ¯
      ä¸¦æä¾›æ‘˜è¦ï¼ŒåŸºæ–¼åˆ†é¡ã€å€‹æ•¸ä»¥åŠç™¼ç”Ÿæ™‚é–“
  - name: assistant_greeting_prompt_12_title
    text: Slack è¨Šæ¯æŸ¥æ‰¾
  - name: assistant_greeting_prompt_12_icon
    text: ğŸ”
  - name: assistant_greeting_prompt_12_message
    text: |
      https://wei840222-home-infra.slack.com/archives/C08VB4JEELX
      é¤¨é•·ç™¼ç”Ÿä»€éº¼äº‹?
