emojis:
  - name: ai_thinking
    emoji: ":loading:"

  - name: google_search_tool_artifact_icon
    emoji: ğŸŒ
  - name: markitdown_crawler_tool_artifact_icon
    emoji: ğŸ“‘

messages:
  - name: content_disclaimer_message
    text: ğŸ¤” AI å¯èƒ½æœƒç™¼ç”ŸéŒ¯èª¤ï¼Œè«‹æŸ¥æ ¸é‡è¦è³‡è¨Šã€‚
  - name: new_conversation_title
    text: é–‹å•Ÿæ–°çš„å°è©±
  - name: new_conversation_message
    text: ğŸ’¡ é–‹å•Ÿæ–°çš„å°è©±
  - name: tool_artifact_title
    text: åƒè€ƒè³‡æ–™
  - name: ai_reply_too_long_warning_message
    text: è¨Šæ¯éé•·ï¼Œå·²æˆªæ–·...

  - name: assistant_placeholder
    text: å•å• AIï¼Œç„¡æ‰€ä¸èƒ½ï¼
  - name: assistant_thinking
    text: æ­£åœ¨æ€è€ƒ...
  - name: assistant_greeting
    text: ä»Šå¤©éçš„å¥½å—?
  - name: assistant_greeting_prompt_1_title
    text: å¹«æˆ‘ç®—æ•¸å­¸
  - name: assistant_greeting_prompt_1_message
    text: 1+1=?
  - name: assistant_greeting_prompt_2_title
    text: å¯«ä¸€éš»ç¨‹å¼
  - name: assistant_greeting_prompt_2_message
    text: å¹«æˆ‘ç”¨ Python å¯«ä¸€å€‹æ’å…¥æ’åºæ³•ã€‚
  - name: assistant_greeting_prompt_3_title
    text: çœ‹çœ‹å¤©æ°£
  - name: assistant_greeting_prompt_3_message
    text: ä»Šå¤©å°åŒ—çš„å¤©æ°£æ€éº¼æ¨£?
